### PR TITLE
Full Image Refactor

### PR DESCRIPTION
**Pull request by waddle77**
This PR encompasses everything that has been done to date for the Yocto Refactor.  The images are the biggest addition, along with being able to update rootfs (in a dual partition mode).  I won't rehash everything, there are several closed PRs that will give a review of each step taken.  The latest additions were changes to the webcam-tools recipe and the gstd recipe.  In order to get the newest version of gstd, splitting up the build was necessary.  Yocto with automake didn't handle a pip install . command really well, so I had to make a new patch file and a new recipe that created pygstc without automake.

Also, no more sourcing the script.  I didn't like how that worked, it was a little confusing and most of the time didn't work the way I wanted it too.  The new script doesn't set up the build environment but its a small price to pay for a working script.

**Testing**
Currently running another full build using the build script to do a little bit of a system test.  The last build did succeed but led to the update of gstd.

**Future**
Test on an actual system.

### CODE REVIEW

**Comment by bvacaliuc** [comment]
Looking good so far...

Screenshot from 2020-09-20 16-24-31

**Comment by waddle77** [comment]
Alright! If you see anything you think will make the process easier, make notes.  Or if things dont work at all, lets fix those too 😄 .  Let's get it to a point that this will work seamlessly. Its hard to tell what fits and what doesn't fit when you work on it in isolation.

**Comment by bvacaliuc** [comment]
finished in 6hrs.  I had left it running overnight. I used a personal machine, rather than the AWS instance this time...

Screenshot from 2020-09-21 14-59-46

I made a branch with my edits but since its a pull request, it won't push to upstream.. I'll just have to commit to this branch...


Now to see about it loading...

**Comment by bvacaliuc** [comment]
generally speaking, the Makefile needs more augmentation or adjustment to simplify the process.  I'm having a hard time following the instructions in the Documentation/ and the README.md w/r/t option number 2 (so as to enable the ability to copy the full image to the eMMC)

**Comment by bvacaliuc** [comment]
Maybe this?
```
bvacaliuc@glowworm-vm:~/ornl-dart-yocto$ sudo MACHINE=var-som-mx6 sources/meta-variscite-fslc/scripts/var_mk_yocto_sdcard/var-create-yocto-sdcard.sh -a -r build_ornl/tmp/deploy/images/var-som-mx6-ornl/var-dev-update-full-image-var-som-mx6-ornl.wic.gz /dev/sdb`
```
Nah, it says:
```
BSP type: YOCTO
================================================
=  Variscite recovery SD card creation script  =
================================================
```
and does nothing...

**Comment by bvacaliuc** [comment]
But if I say instead:
```
bvacaliuc@glowworm-vm:~/ornl-dart-yocto$ sudo MACHINE=var-som-mx6-ornl sources/meta-variscite-fslc/scripts/var_mk_yocto_sdcard/var-create-yocto-sdcard.sh -a -r build_ornl/tmp/deploy/images/var-som-mx6-ornl/var-dev-update-full-image-var-som-mx6-ornl.wic.gz /dev/sdb
BSP type: YOCTO
================================================
=  Variscite recovery SD card creation script  =
================================================
 Usage: MACHINE=<var-som-mx6|imx6ul-var-dart|imx7-var-som> var-create-yocto-sdcard.sh <options> device_node

 options:
 -h		display this Help message
 -s		only Show partition sizes to be written, without actually write them
 -a		Automatically set the rootfs partition size to fill the SD card (leaving spare 4MiB)
 -r ROOTFS_NAME	select an alternative Rootfs for recovery images
 		(default: "/home/bvacaliuc/ornl-dart-yocto/sources/meta-variscite-fslc/scripts/var_mk_yocto_sdcard/../../../..//build_x11/tmp/deploy/images/var-som-mx6-ornl/fsl-image-gui-${MACHINE}")
 -n TEXT_FILE	add a release Notes text file
```
Grr.  Frustrating.

**Comment by waddle77** [comment]
Ok.  I'm an idiot.  The documentation is garbage, and I apologize for that. So I just went through it again and this is the command I used:

```
sudo MACHINE=var-som-mx6-ornl sources/meta-variscite-fslc/scripts/var_mk_yocto_sdcard/var-create-yocto-sdcard.sh -a -r build_ornl/tmp/deploy/images/var-som-mx6-ornl/var-grob-update-full-image-var-som-mx6-ornl /dev/sdb
```

The script uses the tar files to create the SD card image so it appends the file extension for you. That being said there was a bug in the variscite script.  It was using the default image for a couple of things, I fixed it and I'll push that change in a little bit.

**Comment by bvacaliuc** [comment]
ok, better..  Thanks!

```
bvacaliuc@glowworm-vm:~/Desktop/yocto-ornl$ git pull
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 6 (delta 4), reused 6 (delta 4), pack-reused 0
Unpacking objects: 100% (6/6), done.
From https://github.com/uvdl/yocto-ornl
   96a3796..dcca998  DevelopRefactor -> origin/DevelopRefactor
Updating 96a3796..dcca998
Fast-forward
 BuildScripts/var-create-yocto-sdcard.sh | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)
bvacaliuc@glowworm-vm:~/Desktop/yocto-ornl$ pushd ~/ornl-dart-yocto/
~/ornl-dart-yocto ~/Desktop/yocto-ornl ~/Desktop/build/yocto-ornl ~/Projects/horizon31/debian-var
bvacaliuc@glowworm-vm:~/ornl-dart-yocto$ cp ~/Desktop/yocto-ornl/BuildScripts/var-create-yocto-sdcard.sh sources/meta-variscite-fslc/scripts/var_mk_yocto_sdcard/var-create-yocto-sdcard.sh
bvacaliuc@glowworm-vm:~/ornl-dart-yocto$ sudo MACHINE=var-som-mx6-ornl sources/meta-variscite-fslc/scripts/var_mk_yocto_sdcard/var-create-yocto-sdcard.sh -a -r $HOME/ornl-dart-yocto/build_ornl/tmp/deploy/images/var-som-mx6-ornl/var-dev-update-full-image-var-som-mx6-ornl /dev/sdb
BSP type: YOCTO
================================================
=  Variscite recovery SD card creation script  =
================================================
MACHINE=var-som-mx6-ornl
SD card rootfs:  var-dev-update-full-image-var-som-mx6-ornl
Recovery rootfs: var-dev-update-full-image-var-som-mx6-ornl
================================================
Detected removable device /dev/sdb, size=16GB
================================================
Press Enter to continue
```

**Comment by bvacaliuc** [comment]
something is wrong with the reading the board ID register in uboot.  This was fixed after May 11, 2020 in the uboot-imx: https://github.com/uvdl/uboot-imx/commits/iris2

I think its because yocto uses patches, the patch needs to be updated.

**Comment by waddle77** [comment]
Gotcha.  The patch we have currently looks like it's from Jan 29, 2019.  I'll update the patch.

**Comment by bvacaliuc** [comment]
I'm missing the ethernet driver init scripts listed here: https://github.com/uvdl/debian-var/tree/iris2/patches

I need 'init-ksz8795' and 'init-ksz9897' to run for pixc4 and pixc3 respectively.

**Comment by bvacaliuc** [comment]
bummer:
```
root@var-som-mx6-ornl:~# SPI=/sys/bus/spi/devices
root@var-som-mx6-ornl:~# SWREG=$SPI/spi0.0/sw/reg
root@var-som-mx6-ornl:~# CONFIG=0xff
root@var-som-mx6-ornl:~# modprobe -v spi-ksz8795
modprobe: FATAL: Module spi-ksz8795 not found in directory /lib/modules/4.9.88-mx6+g930c98c12bb9
```

this looks like a regression from previous yocto builds.

**Comment by bvacaliuc** [comment]
I was having problem with this on the debian side as well.  It seems like a catching disease.  So the solution may not be simple...

**Comment by bvacaliuc** [comment]
missing the `imx6q-nightcrawler-R0.dtb` file for pixc4

**Comment by bvacaliuc** [comment]
Its still not really ready yet.  I have a machine in that I had built 11 days ago.  I pulled the new updates above, then I did https://github.com/uvdl/yocto-ornl/tree/DevelopRefactor#run-just-the-setup-environment-script and it gave:
```
bvacaliuc@glowworm-vm:~/Desktop/yocto-ornl$ git status
On branch DevelopRefactor
Your branch is up to date with 'origin/DevelopRefactor'.

nothing to commit, working tree clean
bvacaliuc@glowworm-vm:~/Desktop/yocto-ornl$ git log | head -4
commit 01951570aa91f73072868b887155601359e2f0ff
Author: Tyler <waddle77@gmail.com>
Date:   Thu Oct 1 06:18:36 2020 -0700

bvacaliuc@glowworm-vm:~/Desktop/yocto-ornl$ BuildScripts/ornl-setup-yocto.sh -b ~/ornl-dart-yocto
Using Ubuntu Version 18.04

This build is only guaranteed to work with Ubuntu 16.04
Do you wish to proceed [y/N]: y

Current build location base is /home/bvacaliuc


Welcome to Freescale Community BSP

The Yocto Project has extensive documentation about OE including a
reference manual which can be found at:
    http://yoctoproject.org/documentation

For more information about OpenEmbedded see their website:
    http://www.openembedded.org/

You can now run 'bitbake <target>'

Common targets are:
    core-image-minimal
    meta-toolchain
    meta-toolchain-sdk
    adt-installer
    meta-ide-support

Your configuration files at build_ornl have not been touched.

Copying the ORNL local.conf file over... 

cp: cannot stat '/home/bvacaliuc/ornl_layer/build/conf/local.conf': No such file or directory

============================================
Copy of local.conf failed...
============================================
```

There never was ~/ornl_layer/ so my guess is that the script is not taking the command line argument...

**Comment by bvacaliuc** [comment]
**Running this on cades@linuxsystembuilder.ornl.gov**

Ok, so following Tyler's recommendation, I ran 'make environment' which does the needed copies and tells you what setup-environment command is required.  Building the 'var-prod-update-full-image' runs and gives this:
```
ERROR: Task (/home/cades/ornl-dart-yocto/sources/meta-openembedded/meta-oe/recipes-extended/libconfig/libconfig_1.5.bb:do_fetch) failed with exit code '1'
WARNING: Failed to fetch URL git://github.com/RidgeRun/gstd-1.x.git;tag=v0.11.0, attempting MIRRORS if available
ERROR: Fetcher failure: Fetch command export PSEUDO_DISABLED=1; export PATH="/home/cades/ornl-dart-yocto/build_ornl/tmp/sysroots-uninative/x86_64-linux/usr/bin:/home/cades/ornl-dart-yocto/build_ornl/tmp/work/armv7at2hf-neon-fslc-linux-gnueabi/gst-pylibgstc/v0.11.0-r0/recipe-sysroot-native/usr/bin/python3-native:/home/cades/ornl-dart-yocto/sources/poky/scripts:/home/cades/ornl-dart-yocto/build_ornl/tmp/work/armv7at2hf-neon-fslc-linux-gnueabi/gst-pylibgstc/v0.11.0-r0/recipe-sysroot-native/usr/bin/arm-fslc-linux-gnueabi:/home/cades/ornl-dart-yocto/build_ornl/tmp/work/armv7at2hf-neon-fslc-linux-gnueabi/gst-pylibgstc/v0.11.0-r0/recipe-sysroot/usr/bin/crossscripts:/home/cades/ornl-dart-yocto/build_ornl/tmp/work/armv7at2hf-neon-fslc-linux-gnueabi/gst-pylibgstc/v0.11.0-r0/recipe-sysroot-native/usr/sbin:/home/cades/ornl-dart-yocto/build_ornl/tmp/work/armv7at2hf-neon-fslc-linux-gnueabi/gst-pylibgstc/v0.11.0-r0/recipe-sysroot-native/usr/bin:/home/cades/ornl-dart-yocto/build_ornl/tmp/work/armv7at2hf-neon-fslc-linux-gnueabi/gst-pylibgstc/v0.11.0-r0/recipe-sysroot-native/sbin:/home/cades/ornl-dart-yocto/build_ornl/tmp/work/armv7at2hf-neon-fslc-linux-gnueabi/gst-pylibgstc/v0.11.0-r0/recipe-sysroot-native/bin:/home/cades/ornl-dart-yocto/sources/poky/bitbake/bin:/home/cades/ornl-dart-yocto/build_ornl/tmp/hosttools"; export HOME="/home/cades"; git -c core.fsyncobjectfiles=0 remote failed with exit code 128, output:
fatal: Not a git repository (or any of the parent directories): .git

ERROR: Fetcher failure for URL: 'git://github.com/RidgeRun/gstd-1.x.git;tag=v0.11.0'. Unable to fetch URL from any source.
ERROR: Function failed: base_do_fetch
```
(its not the first failure, but its a common theme.  I thought removing the `protocol=https` might help but it doesn't.)  If I do the clone manually on the machine, it works fine:
```
cades@linuxsystembuilder:/tmp$ cd /tmp && git clone git://github.com/RidgeRun/gstd-1.x.git -b v0.11.0
Cloning into 'gstd-1.x'...
remote: Enumerating objects: 6570, done.
remote: Total 6570 (delta 0), reused 0 (delta 0), pack-reused 6570
Receiving objects: 100% (6570/6570), 1.21 MiB | 0 bytes/s, done.
Resolving deltas: 100% (4844/4844), done.
Checking connectivity... done.
Note: checking out '81b48da1c4dc3c1de3167af1c32838a96006edf3'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>
```

**Comment by bvacaliuc** [comment]
confim that on `glowworm` a machine without network restrictions the `environment-update` make target in the [merge/DevelopRefactor](https://github.com/uvdl/yocto-ornl/commit/616ff944977fd29b49a06471db0bee22a064de6c) branch is working.
```
bvacaliuc@glowworm-vm:~/Desktop/yocto-ornl$ make environment-update
bvacaliuc@glowworm-vm:~/Desktop/yocto-ornl$ cd /home/bvacaliuc/ornl-dart-yocto && MACHINE=var-som-mx6-ornl DISTRO=fslc-framebuffer EULA=1 . setup-environment build_ornl
bvacaliuc@glowworm-vm:~/ornl-dart-yocto/build_ornl$ LANG=$LANG bitbake var-prod-update-full-image
```

**Comment by waddle77** [comment]
So now I need to figure out why the other machine is being restricted.  It grabs all the other repos just fine, why is it 🤮 on gstd?

**Pull request merged**
